projects:
  myapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: wkipzjjxwzhabdudxraqfe4ure
      endpoints:
        prod: >-
          https://bfcs62bi6vcjxlyhayy3pjtlr4.appsync-api.us-east-1.amazonaws.com/graphql
